name = "ContextTracking"
uuid = "6cbdd853-f5b8-41ca-9b66-f060deb7aec3"
authors = ["Tom Kwong <tk3369@gmail.com>"]
version = "0.2.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
DataStructures = "0.17"
DocStringExtensions = "0.8"
ExprTools = "0.1"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
