name: TagBot
on:
  push:
    branches:
      - master
  schedule:
    - cron: '17 * * * *'
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
